name: Monitor Vórtx Excel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # <--- ADICIONE ESTA LINHA (Mata o processo se travar)

    steps:
      # ... (resto do código igual)
